### PR TITLE
feat: Make tests work and run green.

### PR DESCRIPTION
**Pull request by KatrinaAS**
First commit is base change that makes tests compile and run, future ones will be fixing broken tests

### CODE REVIEW

**Comment by KatrinaAS** [comment]
note: **This is not ready yet. Do Not Merge**

I will delete this comment and set it to a normal PR once it is ready

**Comment by KatrinaAS** [comment]
Please note: The tests are now destructive on the TEST database, they clear the table once ran

**Review by DanielKrawisz — APPROVED** [review]
Tests have been updated not only to pass, but to avoid reliance on outside APIs and to destruct the test database on completion.

**Comment by KatrinaAS** [comment]
Pulled this back to draft as someone pushed a commit that broke everything again

**Comment by KatrinaAS** [comment]
@GuiDeMa Going to revert the last commit back to previous. With the fact package.json was changed in a few places, package-lock.json can't just me normally merged in. trying just breaks the npm ci

**Comment by KatrinaAS** [comment]
Back ready to pull, merge conflict resolved and tests still green. 🟢

**Review by owenkellogg — APPROVED** [review]
👍 Looks good to me, I approve.

Also, would it make sense to follow the same `$branch` -> `develop` -> `master` pattern we have been using for pow.co? That way we can always deploy the latest develop branch to a staging API for live testing.

**Comment by KatrinaAS** [comment]
> Also, would it make sense to follow the same `$branch` -> `develop` -> `master` pattern we have been using for pow.co? That way we can always deploy the latest develop branch to a staging API for live testing.

Definately sounds good there to me.

**Comment by owenkellogg** [comment]
Then I will set up circle ci to automatically deploy the `develop` branch to `develop.pow.co`

**Comment by owenkellogg** [comment]
@KatrinaAS Will you please update the pull request to make it to `develop` rather than `master` ? That way we can deploy it live and test in a staging environment before pushing it out to the apps and miners.

**Comment by KatrinaAS** [comment]
> @KatrinaAS Will you please update the pull request to make it to `develop` rather than `master` ? That way we can deploy it live and test in a staging environment before pushing it out to the apps and miners.

Done that!

**Pull request merged**
