### PR TITLE
Adding a dev container for ease of developing.

### PR DESCRIPTION
**Pull request by KatrinaAS**

### CODE REVIEW

**Comment by owenkellogg** [comment]
Rather than bringing in the c++ concept of includes, how about simply copying the relevant parts of easy-by into src/ and any required modules into package.json?

**Review by owenkellogg — CHANGES_REQUESTED** [review]
Rather than bringing in the c++ concept of includes, how about simply copying the relevant parts of easy-by into src/ and any required modules into package.json?

**Comment by KatrinaAS** [comment]
> Rather than bringing in the c++ concept of includes, how about simply copying the relevant parts of easy-by into src/ and any required modules into package.json?

I made a fork of easy-b that included the change purely to make it easy to update without getting a more and more out of date copy inside the code that will get more and more stale. To use the fork it is just inside package.json like any other package

**Comment by KatrinaAS** [comment]
Converted this to draft while I add missing services

**Comment by KatrinaAS** [comment]
Added RabbitMQ and Redis to devcontainer

**Comment by KatrinaAS** [comment]
closed, as it shouldnt be pushing into master

**Pull request closed without merging**
